// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2gdEoxd15dGspzID0dtMNkuFQ-WQr198',
    appId: '1:1001625826222:web:bed92f0b60513b33464e3f',
    messagingSenderId: '1001625826222',
    projectId: 'budgetapp-1ed28',
    authDomain: 'budgetapp-1ed28.firebaseapp.com',
    storageBucket: 'budgetapp-1ed28.appspot.com',
    measurementId: 'G-GBZ5YFJKS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC03386JNDAxWeZslaXkR1CsKPabpCSrVI',
    appId: '1:1001625826222:android:611b2dae5d5fd4ce464e3f',
    messagingSenderId: '1001625826222',
    projectId: 'budgetapp-1ed28',
    storageBucket: 'budgetapp-1ed28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW7WGRpXl7kqZcqlg6w-cue412WQEMBw4',
    appId: '1:1001625826222:ios:d8d440a2295bdc9f464e3f',
    messagingSenderId: '1001625826222',
    projectId: 'budgetapp-1ed28',
    storageBucket: 'budgetapp-1ed28.appspot.com',
    iosClientId: '1001625826222-ul6dnbmhgtnfl2mgi415ii5jn9vcmdhm.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW7WGRpXl7kqZcqlg6w-cue412WQEMBw4',
    appId: '1:1001625826222:ios:5f023c0f84d082e3464e3f',
    messagingSenderId: '1001625826222',
    projectId: 'budgetapp-1ed28',
    storageBucket: 'budgetapp-1ed28.appspot.com',
    iosClientId: '1001625826222-460417jhft2einutkufd4hppuur65p63.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetApp.RunnerTests',
  );
}
